name: "Publish Helm chart to ECR"

on:
  workflow_call:
    inputs:
      aws_region:
        required: false
        type: string
        default: "eu-west-2"
      aws_role_to_assume:
        required: true
        type: string
      chart_directory:
        required: false
        type: string
        default: "."
      helm_version:
        required: false
        type: string
        default: ""
      validate_version_tag:
        required: false
        type: boolean
        default: true
      create_repository:
        required: false
        type: boolean
        default: false
      repository_prefix:
        required: false
        type: string
        default: ""
    secrets:
      ecr_account_id:
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Home-Office-Digital/core-cloud-workflow-helm-ecr-actions/actions/setup@1.1.0
        with:
          helm_version: ${{ inputs.helm_version }}
      - id: login
        uses: Home-Office-Digital/core-cloud-workflow-helm-ecr-actions/actions/login@1.1.0
        with:
          aws_region: ${{ inputs.aws_region }}
          role_to_assume: ${{ inputs.aws_role_to_assume }}
          account_id: ${{ secrets.ecr_account_id }}
      - id: package
        uses: Home-Office-Digital/core-cloud-workflow-helm-ecr-actions/actions/package@1.1.0
        with:
          chart_directory: ${{ inputs.chart_directory }}
      - uses: Home-Office-Digital/core-cloud-workflow-helm-ecr-actions/actions/publish@1.1.0
        with:
          registry: ${{ steps.login.outputs.registry }}
          package_path: ${{ steps.package.outputs.package_path }}
          chart_name: ${{ steps.package.outputs.chart_name }}
          chart_version: ${{ steps.package.outputs.chart_version }}
          chart_directory: ${{ inputs.chart_directory }}
          aws_region: ${{ inputs.aws_region }}
          create_repository: ${{ inputs.create_repository }}
          validate_version_tag: ${{ inputs.validate_version_tag }}
          repository_prefix: ${{ inputs.repository_prefix }}
